name: Build and Deploy App
on: workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{hashFiles('**/package-lock.json')}}

      - name: Install packages
        run: |
          npm install

      - name: Linting
        run: |
          npm run lint

      - name: Run Tests
        run: |
          npm run test

      - name: Install packages
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: 'dist'

      - name: Deploy to GitHub Pages
        uses: ./.github/actions/custom-js-actions
        with:
          dist-folder: dist

      - name: Print page url
        run: |
          echo ${{steps.deployment.outputs.page_url}}
