name: Build and Deploy Quiz app to Azure Static web app
on: workflow_dispatch

defaults:
  run:
    working-directory: ./quiz-app/01-starting-project

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{hashFiles('**/package-lock.json')}}

      - name: Install packages
        run: |
          npm install

      - name: Linting
        run: |
          npm run lint

      - name: Run Tests
        run: |
          npm run test

      - name: Install packages
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: publish file name
        id: publish
        run: |
          find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'

      - name: Upload artificats
        uses: actions/upload-artifact@v4
        with:
          name: 'dist-files'
          path: quiz-app/01-starting-project/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
      